codecov:
  notify:
    require_ci_to_pass: false
    after_n_builds: 1

  token: 18fed7a5-a580-47bf-8b77-3316518dd732
coverage:
  status:
    project: false
    patch:
      default:
        target: 100%

comment: false
