codecov:
  notify:
    require_ci_to_pass: false
    after_n_builds: 1

  token: 193d03b5-c86b-4fe9-b1ea-dd35aba1e2f5
coverage:
  status:
    project: false
    patch:
      default:
        target: 99%

comment: false
